## Rubric

Instructions: DELETE this cell before you submit via a `git push` to your repo before deadline. This cell is for your reference only and is not needed in your report. 

 Scoring: Out of 10 points

- Each Developing  => -2 pts
- Each Unsatisfactory/Missing => -4 pts
  - until the score is 0

If students address the detailed feedback in a future checkpoint they will earn these points back






|                                  | **Unsatisfactory**                                                                                                                                                                                                                                                                                                                        | **Developing**                                                                                                                                                                                                       | **Proficient**                                                                                                                                                                                            | **Excellent**                                                                                                                                                                            |
|----------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **EDA relevance**                | EDA is mostly neither relevant to the question nor helpful in figuring out how to address the question. Or the EDA does address the question, but many obviously relevant variables / analyses / figures were not included. | EDA is partly irrelevant/unhelpful. EDA missed one or two obvioulsy relevant analysis (distributions of single variables or relationships between variables) | EDA includes the obviously relevant / helpful variables in addressing the question.                                                              | Thorough EDA fully explored the dataset                                                                                                                 |
| **EDA analysis and description** | Many of the analyses are poor choices (e.g., using means instead of medians for obviously skewed data), or are poorly described in the text, or do not aid understanding the data                                                                                                                                                     | Some of the analyses are poor choices, or are poorly described in the text, or do not aid understanding the data                                                                                                 | All analyses are correct choices. Only one or two have minor issues in the text descriptions supporting them. Mostly they fit well with other elements of the EDA and support understanding the data  | All analyses are correct choices with clear text descriptions supporting them. The figures fit well with the other elements of the EDA, producing a clear understanding of the data. |
| **EDA figures**                  | Many of the figures are poor plot choices (e.g., using a bar plot to represent a time series where it would be better to use a line plot) or have poor aesthetics (including colormap, data point shape/color, axis labels, titles, annotations, text legibility) or do not aid understanding the data                                | Some of the figures are poor plot choices or have poor aesthetics. Some figures do not aid understanding the data                                                                                                | All figures are correct plot choices. Only one or two have minor questionable aesthetic choices. The figures mostly fit well with the other elements of the EDA and support understanding the data    | All figures are correct plot choices with beautiful aesthetics. The figures fit well with the other elements of the EDA, producing a clear understanding of the data.                |

# COGS 108 - EDA Checkpoint

## Authors

Instructions: REPLACE the contents of this cell with your team list and their contributions. Note that this will change over the course of the checkpoints

This is a modified [CRediT taxonomy of contributions](https://credit.niso.org). For each group member please list how they contributed to this project using these terms:
> Analysis, Background research, Conceptualization, Data curation, Experimental investigation, Methodology, Project administration, Software, Visualization, Writing – original draft, Writing – review & editing

Example team list and credits:
- Alice Anderson: Conceptualization, Data curation, Methodology, Writing - original draft
- Bob Barker:  Analysis, Software, Visualization
- Charlie Chang: Project administration, Software, Writing - review & editing
- Dani Delgado: Analysis, Background research, Visualization, Writing - original draft

# Research Question

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Background and Prior Work

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

# Hypothesis

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Data

### Data overview

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your data checkpoint feedback

In [1]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

In [2]:
# Setup code -- this only needs to be run once after cloning the repo!
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
# %pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data

import pandas as pd # used to read

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    { 'url': 'https://drive.google.com/uc?export=download&id=1SIa52W3s6ea8VRpdlpB9XZVN68POCgzI',
      'filename':'snp-500.csv'},
    
    { 'url': 'https://drive.google.com/uc?export=download&id=1IL37hUz1W2Ld99pHsOxwUFZQdUJRAhtj',
      'filename':'gold-usd.csv'},
    
    { 'url': 'https://drive.google.com/uc?export=download&id=1KBZRaleDlIjuY9ebKnkTa4gDKk4RdDqH',
      'filename':'btc-usd.csv'},
    
    { 'url': 'https://drive.google.com/uc?export=download&id=10LUWzsH7iYcek10TJFW_Z2SCXKHPK6Jg',
      'filename':'usd-index.csv'}
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/')

Overall Download Progress:   0%|          | 0/4 [00:00<?, ?it/s]
Downloading snp-500.csv:   0%|          | 0.00/198k [00:00<?, ?B/s]
Overall Download Progress:  25%|██▌       | 1/4 [00:02<00:07,  2.44s/it]

Successfully downloaded: snp-500.csv

Downloading gold-usd.csv:   0%|          | 0.00/173k [00:00<?, ?B/s]
Overall Download Progress:  50%|█████     | 2/4 [00:03<00:03,  1.63s/it]

Successfully downloaded: gold-usd.csv

Downloading btc-usd.csv:   0%|          | 0.00/271k [00:00<?, ?B/s]
Overall Download Progress:  75%|███████▌  | 3/4 [00:04<00:01,  1.36s/it]

Successfully downloaded: btc-usd.csv

Downloading usd-index.csv:   0%|          | 0.00/190k [00:00<?, ?B/s]
Overall Download Progress: 100%|██████████| 4/4 [00:05<00:00,  1.42s/it]

Successfully downloaded: usd-index.csv

### Bitcoin Daily Closing Prices

This dataset contains daily closing prices of Bitcoin (BTC), one of the most widely traded cryptocurrencies. The primary metric in this dataset is:
- Closing Price (`Close`): The final trading price of Bitcoin on a given day, measured in USD. This value reflects the market consensus on Bitcoin's worth at the end of a trading day. Unlike traditional stock markets, cryptocurrency markets are open 24/7, so "daily close" usually refers to the price at 00:00 UTC or another standardized cutoff time.

Other columns that appear in the dataset include:
- Date (`date`): The calender day corresponding to each price entry
- Open, High, Low (`USD`): Optional columns showing the opening, highest, and lowest price for the day; reflecting Bitcoin's daily volitility
- Volume: Another optional column showing the amount, in USD, of 'volume' of Bitcoin units traded that day.

Understanding this data is important for investors, analysts, and researchers interested in price trends, volotility, and correlations with other financial metrics. For instance, extreme fluctuatoins in price can indicate market instability, while trends over time can inform investor stategies and their portfolio diversification.

In [3]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
# Method used to tidy data
def find_missing_dates(df):
    df['Date'] = pd.to_datetime(df['Date']) 
    # Sort just in case
    df = df.sort_values('Date')
    # Create full expected daily range
    full_range = pd.date_range(
        start=df['Date'].min(),
        end=df['Date'].max(),
        freq='D'
    )
    return full_range.difference(df['Date'])

## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
df_btc = pd.read_csv('./data/00-raw/btc-usd.csv')

df_btc = df_btc.drop([0, 1]) # csv file previously had multi-index columns. The column
                             # names are now entries. This removes them.

df_btc = df_btc.rename(columns={ # Rename columns that are useful to us
    'Price': 'Date',
    'Close': 'BTC_USD Close'
}).reset_index(drop=True)

#df_btc = df_btc.drop([13, 14]) # Used to test find_missing_dates function

#missing = find_missing_dates(df_btc) # Test if any dates are missing
#print(missing)

#print(df_btc.columns) # Used to prove that each column has its own variable

#df_btc['Date'].is_unique # Used to prove no repeated dates

#df_btc.info() # Used to prove that each value is a single cell

#df_btc.describe(include='all') #

#print(df_btc)
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

### Dataset #2 of S&P Index

This dataset contains daily observations of Standard & Poor's 500 Index (S&P 500) from 2017 to 2025 and includes six columns: date, close, high, low, open, and volume. The most relevant column is “close”, which serves as a benchmark for market risk sentiment in our evaluation of Bitcoin as an asset. Measured in index points, it records the weighted market capitalization of all 500 stocks divided by the index divisor at 4:00 p.m. ET of each trading day.

Fluctuations in “close” indicates changes in stock market performance relative to the previous day. A rise from 5,000 to 5,050 would indicate a 1% increase in the combined market value. In general, daily fluctuations of ±1% reflect normal noise, a 1-3% change signal reaction to news or reports release, while large daily jumps (e.g., >3%) indicate response to systematic shocks. We note that these thresholds are not deterministic reflections of the market.

In the recorded period, S&P 500 has ranged from around 2,200 in early 2017 to over 6,800 towards the end of 2025.

S&P 500 represents large-cap U.S. firms and may not capture the performance of small-cap stocks, which can limit generalizability. The dataset includes gaps in observations on non-trading days. Despite these limitations, the dataset is obtained from a reliable source (Yahoo Finance) and appropriate for our analysis.

In [4]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
df_snp = pd.read_csv('./data/00-raw/snp-500.csv')

df_snp = df_snp.drop([0, 1]) # csv file previously had multi-index columns. The column
                             # names are now entries. This removes them.

df_snp = df_snp.rename(columns={ # Rename columns that are useful to us
    'Price': 'Date',
    'Close': 'S&P_USD Close'
}).reset_index(drop=True)

#missing = find_missing_dates(df_snp) # Test if any dates are missing
#print(missing)  # The days missing sum to non-trading days

#print(df_snp.columns) # Used to prove that each column has its own variable

#df_snp['Date'].is_unique # Used to prove no repeated dates
#print(missing)
#df_snp.info() # Used to prove that each value is a single cell

df_snp.describe(include='all')

#print(df_snp)

,Date,S&P_USD Close,High,Low,Open,Volume
count,2262,2262,2262,2262,2262,2262
unique,2262,2255,2250,2254,2249,2252
top,2017-01-03,2268.89990234375,4159.77001953125,2881.989990234375,3963.340087890625,3285750000
freq,1,2,2,2,2,2

### Gold Index Daily Prices

This dataset contains daily observations of Gold Futures (GC=F) prices from January 2017 through December 2025. Gold futures are standardized contracts used as a global benchmark for gold price movements. All price values are reported in U.S. dollars (USD) per troy ounce, the standard unit for precious metals trading. The dataset includes six primary variables: Date, Open, High, Low, Close, and Volume.

The Open price represents the first transaction price of the trading session, while the High and Low values capture the maximum and minimum prices observed during the day. The Close price reflects the final traded value and is commonly interpreted as the market’s consensus valuation at the end of trading; for example, a Close price of 1,800 indicates that one troy ounce of gold was valued at $1,800 at market close. Volume measures the number of futures contracts traded and serves as an indicator of market participation and liquidity.

Gold is widely considered a safe-haven asset and an inflation hedge, making it relevant for analyzing financial market behavior during periods of economic uncertainty, including the COVID-19 pandemic. The dataset’s time span allows for comparison of gold price dynamics across pre-pandemic, pandemic, and recovery periods.

**Dataset Concerns and Limitations**

This dataset reflects futures market prices rather than physical spot gold prices, which may introduce speculative and contract-roll effects. Financial markets are also closed on weekends and holidays, resulting in missing calendar dates that represent non-trading periods. Additionally, the raw dataset contains formatting artifacts from the Yahoo Finance export process that require preprocessing to obtain a tidy dataset. Finally, gold prices are influenced by macroeconomic and geopolitical factors not directly captured in this dataset, meaning observed relationships should be interpreted as associative rather than causal.

In [5]:
#### YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
df_gold = pd.read_csv('./data/00-raw/gold-usd.csv')

df_gold = df_gold.drop([0, 1]) # csv file previously had multi-index columns. The column
                             # names are now entries. This removes them.

df_gold = df_gold.rename(columns={ # Rename columns that are useful to us
    'Price': 'Date',
    'Close': 'GOLD_USD Close'
}).reset_index(drop=True)

#missing = find_missing_dates(df_gold) # Test if any dates are missing
#print(missing)

#print(df_gold.columns) # Used to prove that each column has its own variable

#df_gold['Date'].is_unique # Used to prove no repeated dates

#df_gold.info() # Used to prove that each value is a single cell

df_gold.describe(include='all')

#print(df_gold)

,Date,GOLD_USD Close,High,Low,Open,Volume
count,2263,2263,2263,2263,2263,2263
unique,2263,2020,2008,2010,2013,1022
top,2017-01-03,1254.300048828125,1813.5,1463.0999755859375,1794.300048828125,0
freq,1,4,4,4,4,36

### US Dollar Index Prices

Within this dataset there are six columns. They are date, close, high, low, open, and volume. The most important metric that will be used for the project is the close column. The Close column represents the final reported value of the U.S. Dollar Index at the end of each trading session. It is measured in index points. These are unitless values that represent the relative strength of the U.S dollar compared to a basket of major foreign currencies. Those being: the Euro (EUR), Japanese Yen (JPY), British Pound (GBP), Canadian Dollar (CAD), Swedish Krona (SEK), and Swiss Franc (CHF).

The close is the most important daily metric because it serves as the official benchmark for performance measurement. Daily returns are calculated using changes in closing prices. Technical indicators such as the Relative Strength Index (RSI) are also calculated using this metric, which is a tool used to measure the speed and change of price movements. Moreover, the close tells us whether the dollar strengthend or weakened in relative to a previous day. For example, if on some day the dollar closes at 80 and the next day the dollar closes at 90, this means the dollar has strengthened, whereas if the dollar first closed at 90 and then closed at 80 this would mean the dollar has weakened.

For the past few decades, the USD index has fluctuated between 80 and 115. Values above 110 generally reflect a strong dollar, whereas values below 85 suggest a weak dollar.

In short, the close column for the USD Index lets us measure the relative strength and weakness of the US Dollar over a period of time.

There are no major concerns with the data. The data was taken from Yahoo Finance, which is a trusted source for market statistics.

In [6]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
df_usd = pd.read_csv('./data/00-raw/usd-index.csv')

df_usd = df_usd.drop([0, 1]) # csv file previously had multi-index columns. The column
                             # names are now entries. This removes them.

df_usd = df_usd.rename(columns={ # Rename columns that are useful to us
    'Price': 'Date',
    'Close': 'USD Close'
}).reset_index(drop=True)

#missing = find_missing_dates(df_usd) # Test if any dates are missing
#print(missing)

#print(df_usd.columns) # Used to prove that each column has its own variable

#df_usd['Date'].is_unique # Used to prove no repeated dates

#df_usd.info() # Used to prove that each value is a single cell

df_usd.describe(include='all')

#print(df_usd)

,Date,USD Close,High,Low,Open,Volume
count,2264,2264,2264,2264,2264,2264
unique,2264,1283,1323,1269,1290,1
top,2017-01-03,92.2300033569336,97.58000183105469,97.43000030517578,97.01000213623047,0
freq,1,6,7,9,7,2264

### Data Wrangling
We will create three datasets, each representing one of the three eras. Those being: pre-pandemic, pandemic, and post-pandemic.

In [7]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
df_btc = df_btc.drop(columns=['High', 'Low', 'Open', 'Volume'])
df_snp = df_snp.drop(columns=['High', 'Low', 'Open', 'Volume'])
df_gold = df_gold.drop(columns=['High', 'Low', 'Open', 'Volume'])
df_usd = df_usd.drop(columns=['High', 'Low', 'Open', 'Volume'])
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

In [9]:
merged_df = df_btc.merge(df_snp, on='Date').merge(df_gold, on='Date').merge(df_usd, on='Date')

In [10]:
print(merged_df)

            Date       BTC_USD Close     S&P_USD Close      GOLD_USD Close  \
0     2017-01-03  1043.8399658203125    2257.830078125  1160.4000244140625
1     2017-01-04    1154.72998046875           2270.75   1163.800048828125
2     2017-01-05  1013.3800048828125            2269.0   1179.699951171875
3     2017-01-06   902.2009887695312  2276.97998046875  1171.9000244140625
4     2017-01-09   902.8280029296875  2268.89990234375              1183.5
...          ...                 ...               ...                 ...
2256  2025-12-24       87611.9609375   6932.0498046875    4480.60009765625
2257  2025-12-26       87301.4296875  6929.93994140625    4529.10009765625
2258  2025-12-29        87138.140625    6905.740234375    4325.10009765625
2259  2025-12-30       88430.1328125    6896.240234375    4370.10009765625
2260  2025-12-31        87508.828125            6845.5    4325.60009765625

               USD Close
0     103.20999908447266
1     102.69999694824219
2      101.5199966430664
3     102.22000122070312
4     101.93000030517578
...                  ...
2256    97.9800033569336
2257    98.0199966430664
2258   98.04000091552734
2259   98.23999786376953
2260   98.27999877929688

[2261 rows x 5 columns]

In [15]:
df_pre = merged_df.loc[0:799].reset_index(drop=True) # Get pre-pandemic from Jan 2017 to March 10th, 2020 
df_pandemic = merged_df.loc[800:1593].reset_index(drop=True) # Covid was declared a pandemic on March 11th, 2020 by the WHO
df_post = merged_df.loc[1594:2260].reset_index(drop=True) # Covid was declared no longer a Public Health Emergency on May 5th, 2023

In [ ]:
# These were used to create csv files that are on the drive
# df_pre.to_csv('pre_pandemic.csv')
# df_pandemic.to_csv('pandemic.csv')
# df_post.to_csv('post_pandemic.csv')

In [21]:
datafiles = [
    { 'url': 'https://drive.google.com/uc?export=download&id=1nDgMUYt88IHcH-3AYxrEFoBB6mv_kUD7',
      'filename':'pre_pandemic.csv'},

    { 'url': 'https://drive.google.com/uc?export=download&id=1biPTZSg7RicB6l3qeoGtq0XrMTRVLVMp',
      'filename':'pandemic.csv'},
    
    { 'url': 'https://drive.google.com/uc?export=download&id=1pN47PETF8dbzQwJyCqVvEp74vOg_Vxmq',
      'filename':'post_pandemic.csv'}
]

get_data.get_raw(datafiles,destination_directory='data/02-processed')

Overall Download Progress:   0%|          | 0/3 [00:00<?, ?it/s]
Downloading pre_pandemic.csv:   0%|          | 0.00/65.2k [00:00<?, ?B/s]
Overall Download Progress:  33%|███▎      | 1/3 [00:01<00:02,  1.17s/it]

Successfully downloaded: pre_pandemic.csv

Downloading pandemic.csv:   0%|          | 0.00/63.6k [00:00<?, ?B/s]
Overall Download Progress:  67%|██████▋   | 2/3 [00:02<00:01,  1.15s/it]

Successfully downloaded: pandemic.csv

Downloading post_pandemic.csv:   0%|          | 0.00/52.1k [00:00<?, ?B/s]
Overall Download Progress: 100%|██████████| 3/3 [00:04<00:00,  1.35s/it]

Successfully downloaded: post_pandemic.csv

## Results

### Exploratory Data Analysis

Instructions: replace the words in this subsection with whatever words you need to setup and preview the EDA you're going to do.   

Please explicitly load the fully wrangled data you will use from `data/02-processed`.  This is a good idea rather than forcing people to re-run the data getting / wrangling cells above.  Sometimes it takes a long time to get / wrangle data compared to reloading the fixed up dataset.

Carry out whatever EDA you need to for your project in the code cells below.  Because every project will be different we can't really give you much of a template at this point. But please make sure you describe the what and why in text here as well as providing interpretation of results and context.

Please note that you should consider the use of python modules in your work.  Any code which gets called repeatedly should be modularized. So if you run the same pre-processing, analysis or visualiazation on different subsets of the data, then you should turn that into a function or class.  Put that function or class in a .py file that lives in `modules/`.  Import the module you made and use it to get your work done.  For reference see `get_raw()` which is inside `modules/get_data.py`.

#### Section 1 of EDA - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

#### Section 2 of EDA if you need it  - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

## Ethics

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Team Expectations

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Project Timeline Proposal

Instructions: Replace this with your timeline.  **PLEASE UPDATE your Timeline!** No battle plan survives contact with the enemy, so make sure we understand how your plans have changed.  Also if you have lost points on the previous checkpoint fix them